const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const context = { window: {} };
vm.createContext(context);
for (const name of ['progressive-guidance-core.js', 'osteoporosis-evidence-guidance-core.js', 'osteoporosis-longitudinal-summary-core.js', 'proto1-visit-core.js']) {
  vm.runInContext(fs.readFileSync(`static/baseline-audit/${name}`, 'utf8'), context, { filename: name });
}
const g1 = context.window.BaselineProgressiveGuidanceCore;
const g2 = context.window.BaselineOsteoporosisEvidenceGuidance;
const g3 = context.window.BaselineOsteoporosisLongitudinalSummary;
const proto = context.window.OstProto1VisitCore;
const row = (id, date, step4) => ({ encounter_id: id, encounter_date: date, status: 'completed', payload: { internal_uuid: id, step4 } });
const episode = { id: 'ep1', agent: 'denosumab', status: 'active', start_date: '2025-01-01' };
const admin = (id, actual, scheduled = '') => ({ id, agent: 'denosumab', actual_date: actual, scheduled_date: scheduled, status: actual ? 'done' : 'planned' });
function run(history, today = '2026-07-01', currentStep4 = {}) {
  const current = { internal_uuid: 'today', encounter_date: today, encounter_archetype: 'treatment_continuation_or_due_monitoring', step4: currentStep4 };
  const projection = g1.buildLongitudinalProjection(history, { currentInternalUuid: 'today' });
  const contextToday = g1.buildEncounterContext(current, projection);
  const evidence = g2.buildEvidenceContext(current, projection, contextToday, { historicalEncounters: history });
  const plan = g2.mergeEvidenceContributions(g1.buildVisitPlan(contextToday), g2.evaluateEvidenceGuidance(evidence));
  const summary = g3.buildSummary({ encounters: history, projection, currentCase: current, historyStatus: 'loaded' });
  return proto.build({ patientId: 'SYNTHETIC-1', encounters: history, projection, summary, plan, current, historyStatus: 'loaded' });
}
const base = [row('e1', '2025-07-01', { treatment_episodes: [episode], administrations: [admin('a1', '2025-07-01')], decision: { type: 'continue', selected_agent: 'denosumab' }, tasks: [] }), row('e2', '2026-01-01', { treatment_episodes: [episode], administrations: [admin('a2', '2026-01-01')], decision: { type: 'continue', selected_agent: 'denosumab' }, tasks: [] })];
const due = run(base);
assert.equal(due.focus, 'due');
assert.equal(due.last_recorded_actual.actual_date, '2026-01-01');
assert.equal(due.derived_due.date, '2026-07-01');
assert.equal(due.prior_final_decision.type, 'continue');
assert.equal(due.milestones.filter(x => x.type === 'actual').length, 2);
assert.equal(due.milestones.filter(x => x.type === 'plan').length, 0);
assert.equal(due.current_decision, null);
assert.equal(proto.previsit(due).last_recorded_actual.actual_date, due.last_recorded_actual.actual_date);
assert.equal(due.milestones.find(x => x.type === 'actual').source.editor, '4');
assert.equal(due.milestones.find(x => x.type === 'actual').precision, 'day');
const original = JSON.stringify(base);
const corrected = JSON.parse(original);
corrected[1].payload.step4.administrations[0].actual_date = '2026-02-01';
const afterCorrection = run(corrected);
assert.equal(afterCorrection.last_recorded_actual.actual_date, '2026-02-01');
assert.equal(afterCorrection.derived_due, null);
assert.equal(JSON.stringify(base), original, 'the projection must not mutate source records');
const delayed = run(base, '2026-08-15');
assert.equal(delayed.focus, 'delay');
assert.equal(delayed.delay_guidance.rule_id, 'OST_G2_R24_DENOSUMAB_GT7M_REBOUND_ESCALATION');
assert.ok(delayed.delay_guidance.source_refs.length);
const stopped = run([...base, row('e3', '2026-02-01', { treatment_episodes: [{ ...episode, status: 'stopped', end_date: '2026-02-01' }], administrations: [], decision: { type: 'switch', selected_agent: 'zoledronate' }, transition: { type: 'denosumab_exit', next_agent: 'zoledronate', next_agent_date: '2026-07-01' }, tasks: [] })]);
assert.equal(stopped.focus, 'transition');
assert.equal(stopped.derived_due, null);
assert.equal(stopped.prior_final_decision.type, 'switch');
assert.equal(stopped.successor_plan.agent, 'zoledronate');
assert.equal(stopped.milestones.filter(x => x.type === 'actual' && x.label.includes('zoledronate')).length, 0);
const conflict = run([...base, row('e4', '2026-01-10', { treatment_episodes: [episode], administrations: [admin('a2', '2026-01-10')], tasks: [] })]);
assert.equal(conflict.focus, 'verification');
assert.equal(conflict.last_recorded_actual, null);
assert.equal(conflict.derived_due, null);
assert.ok(conflict.uncertainty);
assert.ok(conflict.milestones.some(x => x.type === 'actual'));
const uncertain = run([...base, row('e5', '2026-03-01', { treatment_episodes: [episode], administrations: [admin('planned', '', '2026-03-01')], tasks: [{ id: 't1', type: 'dxa', due_date: '2026-07-01', status: 'planned' }] }), row('e6', '2026-04-01', { treatment_episodes: [episode], administrations: [admin('later', '2026-03-08')], tasks: [{ id: 't2', type: 'dxa', due_date: '2026-06-01', status: 'planned' }] })]);
assert.ok(uncertain.plans.length);
assert.ok(uncertain.reconciliation.some(x => x.kind === 'planned_actual'));
assert.ok(uncertain.reconciliation.some(x => x.kind === 'obligation'));
assert.equal(uncertain.obligations.filter(x => x.status === 'planned').length, 2);
assert.equal(uncertain.reconciliation.every(x => !x.confirmed), true);
assert.ok(uncertain.milestones.some(x => x.type === 'plan' && x.uncertainty));
const unavailable = proto.build({ patientId: 'SYNTHETIC-1', encounters: base, historyStatus: 'unavailable' });
assert.equal(unavailable.last_recorded_actual, null);
assert.equal(unavailable.derived_due, null);
assert.equal(unavailable.uncertainty, 'Protected history unavailable or loading');
assert.equal(proto.previsit(unavailable), null);
console.log('Prototype 1 five synthetic journeys and unavailable-history boundary: PASS');
